### ISSUE TITLE
Getting a reference to map/markers

### ISSUE THREAD

**Issue by dougajmcdonald** [miguelcobain/ember-leaflet#78] opened 2016-06-09 08:38 UTC
I would like to get a reference to the leaflet map instance created by the ember component:

```
{{#leaflet-map lat=lat lng=lng zoom=zoom as |layers|}}
    {{layers.tile url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
{{/leaflet-map}}

```

Or alternatively the markers created by:

```
{{#layers.marker draggable=true lat=marker.lat lng=marker.lng onDragend=(action "updateMarker")}}
{{/layers.marker}}      
```

I'm afraid my ember knowledge is limited, is this possible?

**Comment by miguelcobain** [comment] 2016-06-09 09:35
Duplicate of https://github.com/miguelcobain/ember-leaflet/issues/35

**Closed by miguelcobain** 2016-06-09 09:35 UTC
