### ISSUE TITLE
Update to Leaflet 1

### ISSUE THREAD

**Issue by ssured** [miguelcobain/ember-leaflet#28] opened 2016-01-29 08:49 UTC
It seems leaflet made a lot of progress since 0.7, but it is all 'hidden' in the master 1.0 branch. The release schedule of leaflet is far behind schedule and my guess is that 1.0 should be ok to go. What is your roadmap; do you  want to wait for the stable 1.0, is there a place for a separate ember-leaflet-1-0 addon, or is this repo a place where dev on 1.0 could start?

About my use case; I have some failing maps on mainly mobile Android devices. AFAIK the internals of Leaflet 1.0 changed a lot, so my hope is it fixes some of the weird issues too.

**Comment by miguelcobain** [comment] 2016-01-29 09:25
This is definitely the right place to have that.
Is there any known schedule for leaflet 1.0 stable?

**Comment by ssured** [comment] 2016-01-29 09:36
Well, I saw a presentation of @mourner which was recorded a year ago or so, in which he announced it would be a couple of months but all without guarantees, as it is foss. See https://www.youtube.com/watch?v=2H9g2DBIuLA.
My guess 1.0 beta 2 is more stable than a 'regular' beta. There is quite some activity in the Leaflet repo and possibly there just was not enough time to ship the 1.0.

**Comment by mourner** [comment] 2016-01-29 10:07
Correct. Leaflet beta2 is pretty stable but master even more so, and we planned to label the next release as 1.0 RC1. Just didn't get around actually putting up a release yet, should happen any time these days.

**Comment by ssured** [comment] 2016-01-29 10:09
Cool, thanks for your quick insight!

**Comment by miguelcobain** [comment] 2016-01-29 11:27
I'm psyched with Leaflet 1.0 changes! I knew there were some perf improvements, but not so many of them.

@ssured I want this project to work with leaflet 1.0. The only thing I'm concerned about are the plugins compatibility. Many of them probably don't use 1.0.
Maybe the API didn't change significantly between both Leaflet version and we can support both versions without too much effort.

@mourner (sorry for bothering you again), ember-leaflet doesn't use MultiPolygon and MultiPolyline. So, what are the main API changes from Leaflet stable and 1.0?

**Comment by mourner** [comment] 2016-01-29 11:57
@miguelcobain the biggest breaking public API changes are that custom layers now need to inherit from `Layer` class, and plugins that depended on `viewreset` event will also need to depend on `zoom` event, as far as I remember. Most plugins will either work straight away or require a one-line change.

**Comment by miguelcobain** [comment] 2016-01-29 12:03
@ssured Can you please take a first stab at this? ember-leaflet has tests. You can check if anything breaks.

**Comment by ssured** [comment] 2016-01-29 12:53
@miguelcobain I'll see what I can do. Now I know our goals are quite aligned, so I'll fork this repo and see where we'll end. It will be a spare time project though, I'll let you know when I make progress. Great stuff!

**Comment by ssured** [comment] 2016-01-29 13:11
Not to self, or whoever wants to hack on this. Leaflet builds for master are available on
```
<link href="https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet.css" rel="stylesheet" type="text/css" />
<script src="https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet.js"></script>
```

**Comment by miguelcobain** [comment] 2016-01-29 14:52
@ssured you can probably get beta versions from bower. Since the API is the same, it should work on both master and beta.

Then just change this line accordingly: https://github.com/miguelcobain/ember-leaflet/blob/master/blueprints%2Fember-leaflet%2Findex.js#L18

**Comment by ssured** [comment] 2016-01-30 20:35
This is amazing. Just changing bower to `"leaflet": "1.0.0-beta.2"` and everything still works. Quite some tests do fail, but the documentation pages work fine. Moving up to 1.0 seems a manageable path. Awesome work @mourner!

**Comment by ssured** [comment] 2016-02-03 09:09
Have a look at https://github.com/ssured/ember-leaflet-1/tree/leaflet-master All tests pass. I made one PR on leaflet source, and two tests are now aync. Maybe we should pass the `animate:false` option http://mourner.github.io/Leaflet/reference.html#map-animate to allow for synchronous tests again

**Comment by miguelcobain** [comment] 2016-02-03 09:31
@ssured I don't mind async tests, but it looks like you're using setTimeouts, which can be unpredictable. Some kind of an "onAnimationEnd" event would be better.

I had an idea.
Maybe we could use ember-try to run the tests with leaflet stable and beta!

Btw, looks like your PR was rejected. The issue seems to be deeper.

**Comment by miguelcobain** [comment] 2016-02-03 09:32
If the only problem are popups, looks like we're on a good track!

**Comment by ssured** [comment] 2016-02-03 12:52
The popup thing seems more thorough, see https://github.com/Leaflet/Leaflet/pull/4188 and https://github.com/Leaflet/Leaflet/issues/4189

What I did not do is check all possible options agains the (temporary) docs http://mourner.github.io/Leaflet/reference.html

**Comment by saerdnaer** [comment] 2016-03-15 18:47
@ssured Did you have time to look into the popup problems again?

**Comment by ssured** [comment] 2016-03-15 20:35
To be honest, no... 'My' fork just works for me till now. The popups work, but you need to manually layout your content. Provide a width and height for your popup and all works fine

**Comment by saerdnaer** [comment] 2016-03-15 21:30
Can you provide a link to your fork? Applying https://github.com/ssured/Leaflet/commit/e2daf6dbde44984c2214253a25adb79c5771845f to my local copy didn't work for me.

**Comment by ssured** [comment] 2016-03-16 07:24
https://github.com/ssured/ember-leaflet-1/tree/leaflet-master

**Comment by borisrorsvort** [comment] 2016-04-23 09:38
@miguelcobain Any update for the leaflet v1 update ? 0.7.7 (and current ember-leaflet) is crashing hard on android devices (at least nexus 5) (zoom stuff i think), would be nice to get the update.

If you release a new version, it will leave the time for other plugin to update at their own pace.

**Comment by saerdnaer** [comment] 2016-05-11 21:19
@borisrorsvort you can try if the 1.0.0 rc1 works for you by changing the corresponding line in your bower.json to `"leaflet": "1.0.0-rc.1"` and run `bower install leaflet`.

**Comment by borisrorsvort** [comment] 2016-05-11 21:20
@saerdnaer I'll give it a try thanks

**Comment by borisrorsvort** [comment] 2016-05-11 22:03
@ssured v1 rc1 give several errors:

Events.js:1 Uncaught TypeError: Cannot set property '_leaflet_pos' of undefined
popup.js:88 Uncaught TypeError: Cannot read property 'style' of undefined

**Comment by saerdnaer** [comment] 2016-05-12 10:20
@borisrorsvort Have you tried ssured's branch? 
``npm install "ssured/ember-leaflet-1#leaflet-master" --save-dev``

**Comment by miguelcobain** [comment] 2016-05-12 14:42
I'd love to support leaflet 1 on ember-leaflet.

**Comment by borisrorsvort** [comment] 2016-05-12 14:44
That would be really nice because I can't release my mobile app because it crashes on android every single time. Apparently its fixed in 1.0

**Comment by niamleeson** [comment] 2016-05-12 14:50
I just tried ssured's branch and everything seems to be working fine. I mainly needed the centered touchZoom from leaflet 1.0.0. One issue I'm having is the popup on one of my smaller map component is sitting about 10px higher than normal. It might be my fault, but I haven't looked into it yet.

**Comment by borisrorsvort** [comment] 2016-05-12 14:51
Ok thats good news. I'll also test it with the cluster addons asap. I'll keep you posted

**Comment by niamleeson** [comment] 2016-05-12 14:57
Anyone having issue with popup closing as soon as it is open if you click on the marker to close first?

Click on marker -> popup open -> click on marker -> popup close -> click on marker -> popup opens then closes

If you click on the map to close the marker or even just click on the map once, popup works fine.

**Comment by borisrorsvort** [comment] 2016-05-12 19:34
Just tried it and these seem to work fine (Even on android, no crashing anymore):
```
// bower
"leaflet": "~1.0.0-rc.1",
"leaflet.markercluster": "~1.0.0-rc.1",

// npm
"ember-leaflet": "ssured/ember-leaflet-1#leaflet-master",
"ember-leaflet-marker-cluster": "0.0.3",

```

**Comment by ssured** [comment] 2016-05-13 08:00
Cool you guys are also testing v1 of leaflet. I did not pay too much attention to my branch anymore, as in my app it "just works".

**Comment by v3ss0n** [comment] 2016-06-20 12:07
1.0rc now not sure what are the breaking changes. But looks good to move up i guess?

**Comment by miguelcobain** [comment] 2016-06-20 12:36
We do make some use of private leaflet stuff in ember-leaflet (mainly popups). That may be broken. It's a matter of upgrading the leaflet version, see what tests fail and fix them.

**Comment by v3ss0n** [comment] 2016-06-20 12:44
ok , gonna try that  , just replacing leaflet version in bower as @borisrorsvort  did will work right?

**Comment by miguelcobain** [comment] 2016-06-20 13:04
@v3ss0n just replacing the bower version and eventually make the default blueprint install the correct version: https://github.com/miguelcobain/ember-leaflet/blob/master/blueprints/ember-leaflet/index.js#L18

**Comment by v3ss0n** [comment] 2016-06-20 13:34
thanks a lot, i gonna fork and give a try

**Comment by miguelcobain** [comment] 2016-07-20 10:44
I updated ember-leaflet to work with leaflet `0.7.7` and `1.0.0-rc.2`. It installs `1.0.0-rc.2` by default.
I published it as a pre-release under version `2.2.8-beta.0`.

Please use `ember install ember-leaflet@2.2.8-beta.0` and test it on your project.

There is a known bug in ember that affects ember 2.6+, so some tests are failing on those scenarios.

Addon authors, please update and test your addons with this ember-leaflet version. Some leaflet plugins may not work/need update with leaflet 1.
Leaflet 1 has *a lot* of perf improvements and bug fixes.

/cc @knownasilya @mjanda @canufeel @arschmitz

**Comment by miguelcobain** [comment] 2016-07-20 10:54
@ssured looks like popups are a bit weird. Any idea how to fix it?

**Comment by miguelcobain** [comment] 2016-07-20 11:27
@ssured I fixed the problem. Update to `2.2.8-beta.1` on the way.

**Comment by donaldwasserman** [comment] 2016-07-26 10:45
My failing tests include: 

- 80
- 92
- 93
- 94
- 96 
- 97

Are those the same ones you mentioned?

**Comment by miguelcobain** [comment] 2016-07-26 11:55
@donaldwasserman you get failing tests where? in ember-leaflet itself or on your project?
You can see that the tests are passing in older versions of leaflet.

**Comment by donaldwasserman** [comment] 2016-07-26 13:21
I'm using ember-leaflet 2.2.8-beta.1. 

The tests I reference there are the ember-leaflet tests (updated to include the actual test names). They are all related to 

```
Uncaught Error: Assertion Failed: calling set on destroyed object: <dummy@component:marker-layer::emberXXXX>.popupOpen = [object Boolean]
```

I saw that you said you had all the tests passing, so I don't know if there's something wrong with my setup or the tests are actually failing. 

I'm going to trying to get this into my actual project this afternoon to see what shakes out.

**Comment by miguelcobain** [comment] 2016-07-26 13:39
@donaldwasserman which ember version are you testing against?

**Comment by miguelcobain** [comment] 2016-07-26 13:52
@donaldwasserman so, it seems that tests are passing on phantomJS but not on chrome.

**Comment by v3ss0n** [comment] 2016-08-30 10:50
i have switched to latest master , everthing working .
How to run tests ?

**Comment by miguelcobain** [comment] 2016-08-30 10:52
@v3ss0n i meant some manual testing, to check if everything is working as supposed.
Automated tests are already done in the repo.

If you are an ember-leaflet addon author, you should also run your own automated tests against latest embe-leaflet.

**Comment by v3ss0n** [comment] 2016-08-30 11:01
i haven't run automated testes , i will run later.
For now it looking  good , and extremely smoonth!!

btw: What do you think about mapbox-gl leaflet with custom vectortile support? I am going to give it a try in a while.
I tested it and things are extremely fast http://osm2vectortiles.org

**Comment by v3ss0n** [comment] 2016-08-30 21:11
Let me take that back , i got huge performance problem with `ember-leaflet`  `2.2.8-beta.1` and `leaflet` `1.0.0.rc3` (only tested in ember-leaflet not with raw leafletjs )
@miguelcobain  @mourner  
its faster when there is only a few markers  ( about 20-30) 
but when i tested with 500 markers ember-leaflet with latest   `ember-leaflet`  `2.2.8-beta.1` and `leaflet` `1.0.0.rc3` crippled the browser , almost to a halt.

I falled back and tested with  `ember-leaflet`  `2.2.3` and `leaflet` `0.7.7` , everthing works smooth. Rendered up to 2000 icons with smooth performance.

**Comment by miguelcobain** [comment] 2016-08-30 21:13
@v3ss0n do the markers have popups? Custom icons? Just to track down where the problem is.

**Comment by v3ss0n** [comment] 2016-08-30 21:14
no custom icons , on that test. only default icons.

**Comment by mourner** [comment] 2016-08-30 21:41
@v3ss0n can you set up a JSFiddle test case?

**Comment by v3ss0n** [comment] 2016-08-30 21:43
not sure how i can do that with ember at JSFiddle. but i will setup a repo with ember-cli-mirage, so it can be tested with mock data

**Comment by v3ss0n** [comment] 2016-08-30 22:52
please test this 500 marker points:
https://github.com/v3ss0n/stresstest_ember_leaflet
by default its with ember 2.2.7 and leaflet 0.7.7 . works smooth.
and after upgrading both it comes down to a halt.

**Comment by v3ss0n** [comment] 2016-09-01 22:25
@miguelcobain  @mourner  please check the video.
https://www.youtube.com/watch?v=v0oWqdkZcq8&feature=youtu.be
on the left is the latest `ember-leaflet` with `leaflet 1.0.0-rc.3`
on the right is with `leaflet-0.7.7` , same ember version : 
on the left  i am clicking and draggin for long , and it start only to respond after 2-3 sec
on the right very smooth and responsive.
all dataset and  code is same

**Comment by mourner** [comment] 2016-09-01 22:28
@v3ss0n will check it out, thanks!

**Comment by v3ss0n** [comment] 2016-09-01 22:36
Thanks a lot @mourner  i just tested with latest dev version , same peformance as `1.0.0-rc.3` , very slow.
Both are tested at 1000 markers. Whethere using default icon or custom icons , same performance problem happen at latest leaflet.

**Comment by v3ss0n** [comment] 2016-09-01 22:38
let me know if there other ways you want me to test.

**Comment by v3ss0n** [comment] 2016-09-02 22:07
@mourner  whats your analysis on this? Should i report this at  Leaflet? I think this is directly related to Leaflet?

**Comment by mourner** [comment] 2016-09-02 22:21
@v3ss0n I haven't looked at this yet, will try to find some time to investigate next week.

**Comment by v3ss0n** [comment] 2016-09-02 22:29
@mourner  thanks alot , let me know if more tests needed but the video is quite evident..

**Comment by v3ss0n** [comment] 2016-09-07 14:56
@mourner  anything on this? 
I am sure this regression is quite important for Leaflet 1.0 .

**Comment by v3ss0n** [comment] 2016-09-09 08:47
I guess i will need to make a Raw leaflet example of it and post it at Leaflet mailing list ?

**Comment by ssured** [comment] 2016-09-10 11:16
@v3ss0n thanks for your work here, please link the new issue on the leaflet repo to this one, once you have made it

**Comment by acorncom** [comment] 2016-09-28 05:39
And Leaflet 1 was announced today: http://leafletjs.com/2016/09/27/leaflet-1.0-final.html

**Comment by miguelcobain** [comment] 2016-09-28 22:44
ember-leaflet 3.0 was released today and supports glimmer 2 and leaflet 1 final.
I'm going to close this issue, since it was the main topic.

**Closed by miguelcobain** 2016-09-28 22:44 UTC
Labels: enhancement, help wanted

**Comment by v3ss0n** [comment] 2016-09-29 00:00
Ok i will test with ember-leaflet 3 and leaflet final and then open a new issue if  regression still there.
cc: @mourner
